//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTable
    {
        public long id { get; set; }
        public string Blog { get; set; }
        public System.DateTime Date { get; set; }
        public string Heading { get; set; }
        public string Category { get; set; }
        public string ShortDiscription { get; set; }
        public string FeaturedImage { get; set; }
    }
}
public enum Category
{
    User_Experience,
    Technology,
    Team
}
