//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public long id { get; set; }
        public string jobTitle { get; set; }
        public string location { get; set; }
        public string ShortDiscription { get; set; }
        public string jobintroduction { get; set; }
        public string Yourmission { get; set; }
        public string Skills { get; set; }
        public string BanerImage { get; set; }
    }
}
