//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EWT_PrivateSQREntities1 : DbContext
    {
        public EWT_PrivateSQREntities1()
            : base("name=EWT_PrivateSQREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogTable> BlogTable { get; set; }
        public virtual DbSet<Career> Career { get; set; }
        public virtual DbSet<Login> Login { get; set; }
    }
}
